name = "cloudflare-imgbed"
compatibility_date = "2026-04-23"
pages_build_output_dir = "."

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "my-images"

[[kv_namespaces]]
binding = "IMG_BED"
id = "4821081e136a43fcbfb4ebb1463c306b"
